[package]
name = "nekos"
version = "0.1.0"
authors = ["hyarsan"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde_json = "1.0.39"
regex = "1.1.7"

# [dependencies.serde]
# version = "1.0.89"
# features = ["derive"]
